services:
  auth-db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KC_DB_URL_DB:-keycloakdb}
      POSTGRES_USER: ${KC_DB_USERNAME:-keycloakdbuser}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD:-keycloakdbpw}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${KC_DB_USERNAME:-keycloakdbuser} -d ${KC_DB_URL_DB:-keycloakdb}'" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - "dataportal-auth-db:/var/lib/postgresql/data"

  auth:
    image: quay.io/keycloak/keycloak:26.3.1
    command: ["start", "--import-realm"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://auth-db:5432/${KC_DB_URL_DB:-keycloakdb}"
    volumes:
      - ./init/dataportal-realm.json:/opt/keycloak/data/import/realm.json:ro
    healthcheck:
      test: [
        "CMD-SHELL",
        "exec 3<>/dev/tcp/localhost/9000; \
        echo -en 'GET /health/ready' >&3; \
        # Give the server a moment to respond, then search for 'UP'
        if timeout 3 cat <&3 | grep -m 1 'UP'; then \
          exec 3<&-; exec 3>&-; exit 0; \
        else \
          exec 3<&-; exec 3>&-; exit 1; \
        fi"
      ]
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 20
    depends_on:
      - auth-db

volumes:
  dataportal-auth-db:
