services:
  availability-updater:
    image: ghcr.io/medizininformatik-initiative/dataportal-availability-updater:0.4.1
    extra_hosts:
      - "auth.localhost:host-gateway"
      - "localhost:host-gateway"
    env_file:
      - .env
    volumes:
      - "./auth:/opt/availability-updater/auth"
