services:
  excel2fhir:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - "../:/app/input:ro"
      - "../outputGlobal:/app/outputGlobal"
      - "../outputLocal:/app/outputLocal"
