services:
  excel2fhir:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /workspace
    volumes:
      - "../:/workspace:ro"
      - "../outputGlobal:/workspace/outputGlobal"
