import type { Language } from './i18n'

// Each explanation distinguishes the source simulation from the KDS projection.
const help = {
  population: [
    'Synthea: Zielzahl der Patienten. Wenn bei „Lebende und Verstorbene“ die Ergänzung aktiviert ist, bezieht sich die Zielzahl auf lebende Patienten; verstorbene Patienten werden zusätzlich ausgegeben. Sonst zählt sie Patienten des gewählten Lebensstatus. Auswahlregeln und Versuchsgrenzen können verhindern, dass das Ziel erreicht wird. KDS: Übernommen werden die erfolgreich konvertierten Patienten; erzeugte und übernommene Zahlen werden getrennt angezeigt.',
    'Synthea: Target patient count. With both living and deceased patients and replacement enabled, this counts living patients; deceased patients are additional. Otherwise it counts patients of the selected vital status. Selection rules and attempt limits may prevent reaching the target. KDS: Only successfully converted patients are included; generated and imported counts are shown separately.'
  ],
  minAge: ['Synthea: Untere Altersgrenze am Bezugsdatum; daraus werden Geburtsdaten bestimmt. Bei späterem Simulationsende sind überlebende Personen entsprechend älter. KDS: Geburtsdatum und klinischer Verlauf werden übernommen.', 'Synthea: Minimum age at the reference date, used to determine birth dates. Survivors are older at a later simulation end. KDS: Birth date and the supported clinical history are retained.'],
  maxAge: ['Synthea: Obere Altersgrenze am Bezugsdatum. Sie begrenzt weder das Alter bei früheren Behandlungen noch die Länge der Krankengeschichte. KDS: Geburtsdatum und unterstützte Ereignisse bleiben erhalten.', 'Synthea: Maximum age at the reference date. This does not limit age at earlier treatments or the length of the medical history. KDS: Birth date and supported events are retained.'],
  gender: ['Synthea: Weiblich oder männlich für die gesamte Gruppe vorgeben oder zufällig nach der Bevölkerungsverteilung des US-Orts auswählen. Eine feste Verteilung in kleinen Gruppen ist nicht garantiert. Die Auswahl beeinflusst geschlechtsabhängige Module. KDS: Das erzeugte Geschlecht wird übernommen.', 'Synthea: Restrict the population to female or male patients, or sample from the US location’s population distribution. Small groups have no guaranteed ratio. This affects sex-dependent modules. KDS: The generated gender is retained.'],
  patientSeed: ['Synthea: Startzahl für die Zufallsentscheidungen zur Patientenpopulation und Krankengeschichte. Gleiche Startzahlen, Datumsangaben, Einstellungen und dieselbe Generatorversion ermöglichen reproduzierbare Läufe. KDS: Veränderte Quelldaten verändern auch das Ergebnis der Umwandlung.', 'Synthea: Seed for random choices in the patient population and medical histories. Matching seeds, dates, settings and generator version allow repeatable runs. KDS: Changes to source data also change the converted results.'],
  clinicianSeed: ['Synthea: Separate Startzahl für synthetische Behandler, etwa ihre Namen. Die ursprüngliche FHIR-Ausgabe enthält auch Behandlerdaten. KDS: Persönliche Behandlerdaten werden derzeit nicht übernommen; eine verknüpfte Fachrichtung kann zur Fachabteilungszuordnung beitragen.', 'Synthea: Separate random seed for synthetic clinicians, including their names. Original FHIR output includes clinician data. KDS: Personal clinician data is currently omitted; a linked specialty can contribute to department assignment.'],
  referenceDate: ['Synthea: Stichtag für die gewählte Altersspanne und die Berechnung der Geburtsdaten. Damit die Altersspanne am Simulationsende gilt, Bezugsdatum und Simulationsende auf dasselbe Datum setzen. KDS: Die daraus entstehenden Geburtsdaten werden übernommen.', 'Synthea: Date to which the age range applies, used to calculate birth dates. Use the same reference and end dates for the desired age at simulation end. KDS: The resulting birth dates are retained.'],
  endDate: ['Synthea: Bis zu diesem Datum wird der Lebensverlauf simuliert, sofern die Person nicht vorher stirbt. Ein späteres Ende kann neue Behandlungen und geänderte Krankheitszustände erzeugen. KDS: Unterstützte Ereignisse und der Todeszeitpunkt werden übernommen; der Kontaktstatus wird aus den Kontaktzeiten abgeleitet.', 'Synthea: Simulate life until this date or earlier death. A later end may generate additional treatments and changed disease states. KDS: Supported events and time of death are retained; encounter status is derived from encounter times.'],
  state: ['Synthea: US-Bundesstaat als geografische Grundlage für Bevölkerungsdaten und das Versorgungsumfeld. Ein Wechsel kann Patienten und Verläufe verändern. KDS: US-Namen und Wohnadressen werden durch synthetische deutsche Angaben ersetzt; die Simulation bleibt US-geprägt.', 'Synthea: US state supplying geographic population data and the care environment. Changing it may change patients and histories. KDS: US names and home addresses are replaced with synthetic German details; the simulation remains based on US data.'],
  city: ['Synthea: Auf einen Ort im gewählten US-Bundesstaat begrenzen. Ohne Auswahl werden Orte innerhalb des Bundesstaats gewählt. KDS: Der US-Wohnort wird durch eine synthetische deutsche Adresse ersetzt; die zugrunde liegenden klinischen Daten stammen weiter aus der Synthea-Simulation.', 'Synthea: Restrict generation to a city in the selected US state. Without a selection, locations within the state are used. KDS: The US home address is replaced with a synthetic German address; clinical data still comes from the Synthea simulation.'],
  yearsOfHistory: ['Synthea: Anzahl der Jahre vor Simulationsende, die exportiert werden. 0 bedeutet gesamte Historie. Ältere noch aktive Erkrankungen und Medikamente können erhalten bleiben. Die Lebensgeschichte wird trotzdem vollständig simuliert. KDS: Für die Umwandlung stehen nur die exportierten Daten zur Verfügung. Ein kürzerer Zeitraum kann den Umfang der klinischen Daten und die Dateigröße verringern.', 'Synthea: Years before simulation end to include in the export. 0 means the full history. Older active conditions and medications may remain. The full life history is still simulated. KDS: Only exported source content is available for conversion; a short history can reduce clinical coverage and file size.'],
  patientFilter: ['Synthea: Nur am Simulationsende Lebende, nur Verstorbene oder beide behalten. Erfüllt ein simulierter Patient die Vorgabe nicht, wird stattdessen ein weiterer Patient simuliert. KDS: Diese Auswahl bestimmt die importierte Patientengruppe; Todesangaben werden übernommen.', 'Synthea: Keep only patients alive at simulation end, only deceased patients, or both. Nonmatching candidates are discarded and replaced. KDS: This selects the imported cohort; death information is retained.'],
  keepModule: ['Synthea: Zusätzliches Auswahlkriterium für die simulierten Patienten. Es erzeugt keine Erkrankung. Seltene oder widersprüchliche Kriterien benötigen viele Versuche oder führen zum Abbruch. KDS: Der Filter gilt vor Export und Umwandlung; seine Kriterien müssen wegen des begrenzten Exportzeitraums und nicht übernommener Inhalte im KDS-Ergebnis nur teilweise erkennbar sein.', 'Synthea: Additional criterion simulated patients must meet to be retained. It does not cause a disease. Rare or contradictory criteria require many attempts or fail. KDS: Filtering precedes export and conversion; history limits and mapping gaps may prevent the selection criterion from being fully visible in KDS output.'],
  singlePersonSeed: ['Synthea: Startzahl für einen einzelnen Patienten, verwendbar bei Zielzahl 1. Sie steuert dessen Zufallsentscheidungen; die übrigen Einstellungen wirken weiterhin. KDS: Die unterstützten Inhalte dieses Patienten werden umgewandelt.', 'Synthea: Seed for one individual, available when the target count is 1. It controls that individual’s random choices; other settings still apply. KDS: Supported content for this patient is converted.'],
  timestepDays: ['Synthea: Abstand der Simulationsschritte in Tagen. Kleinere Schritte können zeitliche Abläufe feiner auflösen und benötigen mehr Rechenzeit. Größere Schritte können Zeitpunkte und Ergebnisse verändern. KDS: Die unterstützten erzeugten Zeitpunkte werden übernommen; die Zeitangaben werden durch diese Einstellung nicht nachträglich gerundet.', 'Synthea: Simulation step length in days. Shorter steps may resolve events more finely and require more computation. Longer steps may change event times and outcomes. KDS: Supported generated times are retained; this is not an output rounding setting.'],
  maxAttempts: ['Synthea: Obergrenze der Versuche, einen passenden Patienten für die Auswahlkriterien zu finden. Bei unerfüllbaren Kriterien kann der Lauf abbrechen. Eine höhere Grenze garantiert keinen Erfolg. KDS: Bestimmt, ob ausreichend Quelldaten für die Umwandlung entstehen; bereits entstandene Teilergebnisse können verfügbar sein.', 'Synthea: Maximum attempts to find a patient matching the criteria. Impossible criteria may cause the run to fail. A higher limit does not guarantee success. KDS: Determines whether enough source data is available; partial results may exist.'],
  overflow: ['Synthea: Bei „Lebende und Verstorbene“ werden Verstorbene zusätzlich ausgegeben und durch weitere Patienten ergänzt, bis die Zielzahl lebender Patienten erreicht ist. Die Gesamtzahl kann höher liegen. Bei nur einem Lebensstatus hat diese Einstellung keine zusätzliche Wirkung. KDS: Zusätzliche Patienten werden ebenfalls zur Umwandlung übergeben.', 'Synthea: When including both living and deceased patients, deceased patients are exported additionally and replaced until the living target is reached. Total count may be higher. This has no additional effect when only one vital status is selected. KDS: Additional patients are also passed to conversion.'],
  veteranPopulation: ['Synthea: Simuliert alle Patienten als ehemalige Angehörige der US-Streitkräfte. Die dafür geltenden Regeln können ihre medizinische Versorgung beeinflussen. KDS: Der Veteranenstatus selbst wird derzeit nicht abgebildet. Unterstützte klinische Ereignisse werden übernommen.', 'Synthea: Forces US veteran population membership, which can affect care through applicable rules. KDS: Veteran status itself is currently not mapped; supported clinical events are retained.'],
  modules: ['Synthea: Auswahl der Krankheits- und Versorgungsabläufe, die simuliert werden. Keine Auswahl bedeutet alle verfügbaren Module. Bei gezielter Auswahl bleiben Kernabläufe und benötigte Untermodule aktiv. Bedingungen und Wahrscheinlichkeiten entscheiden, ob ein Patient erkrankt oder eine Behandlung erhält. KDS: Unterstützte Diagnosen, Befunde, Medikamente, Prozeduren und Kontakte werden abgebildet. Welche Inhalte in KDS-Ressourcen umgewandelt werden können, hängt von den vorhandenen Zuordnungen ab. Nicht übernommene Inhalte stehen im Importbericht. Bei sehr enger Modulauswahl entstehen möglicherweise keine übernehmbaren Diagnosen; dadurch kann die KDS-Umwandlung scheitern.', 'Synthea: Select the disease and care processes to simulate. An empty selection enables all available modules. Core processes and required submodules remain active with a restricted selection. Conditions and probabilities determine whether a patient develops a disease or receives care. KDS: Supported diagnoses, observations, medications, procedures and encounters are mapped. Selection does not extend mapping coverage; omissions are recorded in the import report. Very narrow selections may yield no importable diagnoses and fail KDS conversion.'],
  outputMode: ['KDS-FHIR: Die Synthea-Daten über die Excel-Vorlage in KDS-Ressourcen umwandeln, deutsche Personendaten einsetzen und die gewählte KDS-Konfiguration anwenden.\n\nSynthea-FHIR: Ursprüngliche FHIR-R4-Ressourcen einschließlich US-Personen-, Organisations- und Behandlerdaten als JSON erzeugen. KDS-Konfigurationen werden dabei nicht angewendet.', 'KDS FHIR: Convert the Synthea data through our Excel/KDS mapping, substitute German identities and apply the selected KDS configuration.\n\nSynthea FHIR: Generate original FHIR R4 JSON resources, including US patient, organization and clinician data. KDS configurations do not apply.']
} as const
export type HelpKey = keyof typeof help
export function generationHelp(language: Language, key: HelpKey): string { return help[key][language === 'de' ? 0 : 1] }

const rules: Record<string, [string, string, string, string]> = {
  'keep_diabetes.json': ['Aktiver Typ-2-Diabetes', 'Active type 2 diabetes', 'Prüft den aktiven SNOMED-Code 44054006.', 'Checks active SNOMED code 44054006.'],
  'keep_diabetes_no_dr.json': ['Typ-2-Diabetes ohne aktive NPDR', 'Type 2 diabetes without active NPDR', 'Aktiver Typ-2-Diabetes (44054006), ohne aktive nichtproliferative diabetische Retinopathie (1551000119108). Andere Netzhauterkrankungen werden nicht allgemein ausgeschlossen.', 'Active type 2 diabetes (44054006) without active nonproliferative diabetic retinopathy (1551000119108). This does not exclude all other retinal disease.'],
  'keep_hospice.json': ['Hospizmerkmal vorhanden', 'Hospice attribute present', 'Prüft, ob Syntheas internes Merkmal „hospice“ gesetzt ist.', 'Checks whether Synthea’s internal hospice attribute is present.'],
  'keep_medicare_beneficiaries.json': ['US-Medicare-Auswahlregel', 'US Medicare selection rule', 'Behält Personen ab 65 Jahren oder mit bestimmten US-Versicherungs-, Behinderungs- oder Nierenmerkmalen. Die Regel umfasst auch Medicaid und ist kein Nachweis einer Medicare-Mitgliedschaft.', 'Keeps people aged 65 or older or matching specified US insurance, disability or kidney criteria. The rule also includes Medicaid and does not prove Medicare membership.'],
  'keep_npdr.json': ['Aktive nichtproliferative diabetische Retinopathie', 'Active nonproliferative diabetic retinopathy', 'Diabetische Netzhauterkrankung ohne die kennzeichnende Gefäßneubildung; prüft aktiven Code 1551000119108. Eine zusätzliche proliferative Form wird von dieser Regel nicht ausgeschlossen.', 'Diabetic retinal disease without the characteristic new vessel growth; checks active code 1551000119108. This rule does not exclude an additional proliferative form.'],
  'keep_npdr_no_pdr.json': ['Aktive NPDR ohne aktive proliferative Form', 'Active NPDR without active proliferative disease', 'Prüft aktive nichtproliferative diabetische Retinopathie (1551000119108) und schließt den aktiven Code der proliferativen Form (1501000119109) aus.', 'Requires active nonproliferative diabetic retinopathy (1551000119108) and excludes active proliferative disease (1501000119109).'],
  'keep_pdr.json': ['Aktive proliferative diabetische Retinopathie', 'Active proliferative diabetic retinopathy', 'Diabetische Netzhauterkrankung mit Gefäßneubildung; prüft aktiven Code 1501000119109.', 'Diabetic retinal disease with new vessel growth; checks active code 1501000119109.'],
  'must_have_cabg.json': ['Koronare Bypassoperation', 'Coronary artery bypass surgery', 'Prüft, ob eine Bypassoperation mit Code 232717009 oder 418824004 in Syntheas internem Verlauf vorhanden ist.', 'Checks for coronary bypass surgery code 232717009 or 418824004 in Synthea’s internal history.'],
  'must_have_cardiac_surgery.json': ['Herzoperation: Bypass oder Aortenklappe', 'Cardiac surgery: bypass or aortic valve', 'Prüft das Merkmal „cardiac_surgery“ oder die vorgesehenen Codes für koronaren Bypass, Aortenklappenersatz oder -rekonstruktion.', 'Checks the cardiac_surgery attribute or the specified codes for coronary bypass, aortic valve replacement or repair.']
}
export function selectionRule(language: Language, id: string, fallback: string) {
  const item = rules[id]
  const index = language === 'de' ? 0 : 1
  return { name: item?.[index] ?? fallback, description: item?.[index + 2] ?? generationHelp(language, 'keepModule') }
}
export type ModuleDescription = { id: string; name: string; examples?: Record<string, string[]> }
export function moduleHelp(language: Language, module: ModuleDescription): string {
  const kinds: Record<string, [string, string]> = { ConditionOnset: ['Diagnosen', 'Conditions'], Procedure: ['Prozeduren', 'Procedures'], MedicationOrder: ['Medikamente', 'Medications'], Observation: ['Befunde', 'Observations'], Encounter: ['Kontakte', 'Encounters'] }
  const examples = Object.entries(module.examples ?? {}).flatMap(([kind, values]) => {
    const details = values.filter(value => value.trim().toLowerCase() !== module.name.trim().toLowerCase()).slice(0, 3)
    return details.length ? [`${kinds[kind]?.[language === 'de' ? 0 : 1] ?? kind}: ${details.join('; ')}`] : []
  }).join('\n')
  return examples ? (language === 'de' ? 'Beispiele für erzeugte Inhalte (Originalbezeichnungen):\n' : 'Examples of generated content (original labels):\n') + examples : ''
}
